/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/p1/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Opportunity
         * @description Analyzes a Land Opportunity (Garimpo) and returns a Go/No-Go decision.
         */
        post: operations["analyze_opportunity_p1_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/thesis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Thesis
         * @description Generates an investment thesis based on the provided financial JSON.
         */
        post: operations["generate_thesis_analyze_thesis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wizard/p2/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze P2 Economic
         * @description P2: Dinâmica Econômica Analysis
         *
         *     Calculates P2i-Lead score (0-50) based on:
         *     - Leading indicators: Employment, Credit, Confidence
         *     - Lagging indicators: IPCA, PIB, Selic
         *     - Contextual factors: Population, Metropolitan status
         *
         *     Gate: P2i-Lead >= 28 for GO
         */
        post: operations["analyze_p2_economic_wizard_p2_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wizard/p4/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze P4 Vocation
         * @description P4: Vocação Imobiliária Analysis
         *
         *     3-Pillar Attractiveness Matrix:
         *     - Pilar 1: Zoning & Potential (30%)
         *     - Pilar 2: Centrality & Accessibility (40%)
         *     - Pilar 3: Infrastructure (30%)
         *
         *     Returns product recommendation and decision.
         */
        post: operations["analyze_p4_vocation_wizard_p4_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wizard/p5/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze P5 Legal
         * @description P5: Legal Due Diligence Analysis
         *
         *     Binary Gate checking:
         *     - Ownership status
         *     - Environmental restrictions
         *     - Urban/Zoning compliance
         *     - Fiscal situation
         *     - Judicial issues
         *
         *     Returns PASS/FAIL with detailed findings.
         */
        post: operations["analyze_p5_legal_wizard_p5_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wizard/p6/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze P6 Demand
         * @description P6: Qualified Demand Analysis
         *
         *     5-Stage Funnel:
         *     1. Total Families
         *     2. Income-Qualified
         *     3. Product-Fit
         *     4. Purchase Intent
         *     5. Effective Demand
         */
        post: operations["analyze_p6_demand_wizard_p6_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wizard/p7/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze P7 Supply
         * @description P7: Supply & Market Analysis
         *
         *     Analyzes:
         *     - Competitor inventory
         *     - Pricing benchmarks
         *     - Market saturation
         */
        post: operations["analyze_p7_supply_wizard_p7_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wizard/p8/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze P8 Absorption
         * @description P8: Sales Velocity (VSO) Analysis
         *
         *     Calculates:
         *     - Monthly sales velocity
         *     - Absorption timeline
         *     - Demand/Supply ratio impact
         */
        post: operations["analyze_p8_absorption_wizard_p8_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wizard/p9/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze P9 Validation
         * @description P9: Strategic Validation (Gate 4:1)
         *
         *     Final market validation before P10:
         *     - 4:1 Demand:Supply ratio
         *     - Absorption timeline check
         *     - Price competitiveness
         */
        post: operations["analyze_p9_validation_wizard_p9_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wizard/session/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Wizard Session
         * @description Create a new wizard session.
         *
         *     Persiste no Supabase para sobreviver restarts do servidor.
         *     Fallback para in-memory se tabela não existir.
         */
        post: operations["create_wizard_session_wizard_session_create_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wizard/session/save-step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Wizard Step
         * @description Save step data to session.
         *
         *     Atualiza no Supabase ou fallback in-memory.
         */
        post: operations["save_wizard_step_wizard_session_save_step_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wizard/session/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wizard Session
         * @description Get wizard session data.
         *
         *     Busca no Supabase ou fallback in-memory.
         */
        get: operations["get_wizard_session_wizard_session__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Wizard Session
         * @description Delete a wizard session (soft delete).
         */
        delete: operations["delete_wizard_session_wizard_session__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wizard/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Wizard Sessions
         * @description List all wizard sessions for the current user.
         *
         *     Query params:
         *     - status: 'active', 'completed', or 'deleted'
         *     - limit: max number of sessions to return
         */
        get: operations["list_wizard_sessions_wizard_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wizard/session/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Wizard Session
         * @description Mark a wizard session as completed.
         */
        post: operations["complete_wizard_session_wizard_session__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint for load balancers and monitoring.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Cache Metrics
         * @description Retorna estatísticas do cache do SearchEngine (Serper).
         *
         *     Métricas:
         *     - hits: Quantas vezes o cache foi utilizado
         *     - misses: Quantas vezes precisou chamar a API
         *     - hit_rate: Percentual de eficiência do cache
         *     - api_calls_saved: Chamadas de API economizadas ($$)
         */
        get: operations["get_cache_metrics_metrics_cache_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Simulations
         * @description List simulations for the authenticated user's portfolio view.
         *     Requires JWT authentication.
         */
        get: operations["list_simulations_simulations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulations/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Recent Simulations
         * @description Get recent simulations for the authenticated user.
         */
        get: operations["get_recent_simulations_simulations_recent_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/{simulation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Simulation
         * @description Retrieves the status and result of a simulation.
         *     Requires JWT authentication.
         */
        get: operations["get_simulation_simulation__simulation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulation/{simulation_id}/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Simulation Status
         * @description SSE Endpoint para streaming de status de simulação.
         *
         *     Substitui o polling do frontend por Server-Sent Events.
         *     O cliente recebe atualizações em tempo real sem fazer requisições repetidas.
         *
         *     Autenticação via query param (SSE não suporta headers customizados):
         *     ```
         *     GET /simulation/{id}/stream?token=JWT_TOKEN
         *     ```
         *
         *     Uso no frontend:
         *     ```javascript
         *     const token = localStorage.getItem('access_token');
         *     const eventSource = new EventSource(`/simulation/{id}/stream?token=${token}`);
         *     eventSource.addEventListener('completed', (e) => {
         *         const data = JSON.parse(e.data);
         *         console.log('Resultado:', data.result);
         *         eventSource.close();
         *     });
         *     ```
         *
         *     Eventos emitidos:
         *     - status: Atualização periódica (PENDING/PROCESSING)
         *     - completed: Simulação finalizada com sucesso
         *     - failed: Simulação falhou
         *     - timeout: Stream encerrado por timeout (5 min)
         *     - error: Erro ao buscar simulação
         */
        get: operations["stream_simulation_status_simulation__simulation_id__stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calculate/quick": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Calculate Quick
         * @description Async Simulation Endpoint.
         *
         *     Security:
         *     - Requires JWT authentication
         *     - Rate limited (30 req/min for simulations)
         *
         *     Dispatches job to Worker via Cloud Tasks (or local stub).
         *     Returns 202-like response with SimulationID.
         */
        post: operations["calculate_quick_calculate_quick_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Returns information about the currently authenticated user.
         *     Useful for frontend to verify authentication status.
         */
        get: operations["get_current_user_info_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisRequest */
        AnalysisRequest: {
            /** Financial Data */
            financial_data: Record<string, never>;
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            /** Thesis */
            thesis: string;
        };
        /**
         * CompetitorInput
         * @description Competitor project input.
         */
        CompetitorInput: {
            /** Name */
            name: string;
            /** Developer */
            developer: string;
            /** Total Units */
            total_units: number;
            /** Units Sold */
            units_sold: number;
            /** Units Available */
            units_available: number;
            /** Price Per Sqm */
            price_per_sqm: number;
            /** Launch Date */
            launch_date?: string | null;
            /**
             * Product Type
             * @default LOTEAMENTO
             */
            product_type: string;
        };
        /** ESGAttributes */
        ESGAttributes: {
            /** @default NONE */
            certification: components["schemas"]["ESGCertification"];
            /**
             * Green Premium
             * @description Projected value increase due to ESG (RICS Adjusted NPV)
             * @default 0
             */
            green_premium: number;
            /**
             * Brown Discount
             * @description Projected value decrease due to lack of ESG
             * @default 0
             */
            brown_discount: number;
            /** Carbon Footprint Tonnes */
            carbon_footprint_tonnes?: number | null;
        };
        /**
         * ESGCertification
         * @enum {string}
         */
        ESGCertification: "LEED" | "BREEAM" | "AQUA" | "WELL" | "EDGE" | "NONE";
        /**
         * GoNoGoDecision
         * @enum {string}
         */
        GoNoGoDecision: "GO" | "NO_GO" | "CAUTION" | "HOLD";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MarketCyclePhase
         * @enum {string}
         */
        MarketCyclePhase: "RECUPERACAO" | "EXPANSAO" | "DESACELERACAO" | "RECESSAO";
        /** P10FinancialInput */
        P10FinancialInput: {
            /** Total Units */
            total_units: number;
            /** Sales Price Avg */
            sales_price_avg: number | string;
            /** Construction Cost Total */
            construction_cost_total: number | string;
            /** Land Cost */
            land_cost: number | string;
            /** Development Months */
            development_months: number;
            /**
             * Use Ret Taxation
             * @description Apply 4% RET on Gross Revenue
             * @default true
             */
            use_ret_taxation: boolean;
            /**
             * Funding Model
             * @description SBPE (Traditional) vs ASSOCIATIVO (MCMV/Caixa)
             * @default SBPE
             */
            funding_model: string;
            /**
             * Permuta Physical Pct
             * @description Percentage of units given to land owner
             * @default 0
             */
            permuta_physical_pct: number;
            /**
             * Incc Annual Rate
             * @description Inflation index for Construction costs
             * @default 0.06
             */
            incc_annual_rate: number;
            /**
             * Ipca Annual Rate
             * @description Inflation index for Sales/Revenue
             * @default 0.045
             */
            ipca_annual_rate: number;
        };
        /** P10FinancialOutput */
        "P10FinancialOutput-Input": {
            /** Npv */
            npv: number | string;
            /** Irr */
            irr: number;
            /** Roe */
            roe: number;
            /** Payback Months */
            payback_months: number;
            /** Exposure Max */
            exposure_max: number | string;
            /** Esg Adjusted Npv */
            esg_adjusted_npv: number | string;
            /**
             * Real Option Land Value
             * @description Black-Scholes Value
             * @default 0
             */
            real_option_land_value: number | null;
        };
        /** P10FinancialOutput */
        "P10FinancialOutput-Output": {
            /** Npv */
            npv: string;
            /** Irr */
            irr: number;
            /** Roe */
            roe: number;
            /** Payback Months */
            payback_months: number;
            /** Exposure Max */
            exposure_max: string;
            /** Esg Adjusted Npv */
            esg_adjusted_npv: string;
            /**
             * Real Option Land Value
             * @description Black-Scholes Value
             * @default 0
             */
            real_option_land_value: number | null;
        };
        /** P1GarimpoInput */
        P1GarimpoInput: {
            /** Location Municipality */
            location_municipality: string;
            /** Location Neighborhood */
            location_neighborhood: string;
            /** Area Sqm */
            area_sqm: number;
            /** Asking Price */
            asking_price: number | string;
        };
        /** P1GarimpoOutput */
        P1GarimpoOutput: {
            cycle_phase: components["schemas"]["MarketCyclePhase"];
            /** Score Attractiveness */
            score_attractiveness: number;
            decision: components["schemas"]["GoNoGoDecision"];
        };
        /**
         * P2Request
         * @description P2 Analysis Request.
         */
        P2Request: {
            /** Municipality */
            municipality: string;
            /**
             * Municipality Population
             * @default 50000
             */
            municipality_population: number;
            /**
             * Is Metropolitan
             * @default false
             */
            is_metropolitan: boolean;
        };
        /**
         * P4Request
         * @description P4 Analysis Request.
         */
        P4Request: {
            /** Municipality */
            municipality: string;
            /** Neighborhood */
            neighborhood: string;
            /** Latitude */
            latitude?: number | null;
            /** Longitude */
            longitude?: number | null;
            /**
             * Zoning Type
             * @default ZR2
             */
            zoning_type: string;
            /**
             * Max Height Floors
             * @default 4
             */
            max_height_floors: number;
            /**
             * Max Coverage Ratio
             * @default 0.6
             */
            max_coverage_ratio: number;
            /**
             * Max Floor Area Ratio
             * @default 2
             */
            max_floor_area_ratio: number;
            /**
             * Distance City Center Km
             * @default 2
             */
            distance_city_center_km: number;
            /**
             * Distance Main Avenue Km
             * @default 0.5
             */
            distance_main_avenue_km: number;
            /**
             * Public Transport Available
             * @default true
             */
            public_transport_available: boolean;
            /** Distance Metro Station Km */
            distance_metro_station_km?: number | null;
            /**
             * Infrastructure Level
             * @default COMPLETE
             */
            infrastructure_level: string;
            /**
             * Has Paved Access
             * @default true
             */
            has_paved_access: boolean;
            /**
             * Has Water Network
             * @default true
             */
            has_water_network: boolean;
            /**
             * Has Sewage Network
             * @default true
             */
            has_sewage_network: boolean;
            /**
             * Has Electricity
             * @default true
             */
            has_electricity: boolean;
            /**
             * Has Gas Network
             * @default false
             */
            has_gas_network: boolean;
            /**
             * Has Fiber Optic
             * @default false
             */
            has_fiber_optic: boolean;
            /**
             * Land Area Sqm
             * @default 5000
             */
            land_area_sqm: number;
            /**
             * Land Price Per Sqm
             * @default 150
             */
            land_price_per_sqm: number;
            /**
             * Target Segment
             * @default MEDIO
             */
            target_segment: string;
        };
        /** P4VocationOutput */
        P4VocationOutput: {
            /** Score Zoning */
            score_zoning: number;
            /** Score Centrality */
            score_centrality: number;
            /** Score Density */
            score_density: number;
            /** Total Score */
            total_score: number;
            recommended_product: components["schemas"]["ProductType"];
        };
        /**
         * P5Request
         * @description P5 Analysis Request.
         */
        P5Request: {
            /**
             * Land Registration Number
             * @description Matrícula do imóvel
             */
            land_registration_number: string;
            /** Municipality */
            municipality: string;
            /**
             * Notary Office
             * @description Cartório de registro
             * @default 1º Ofício
             */
            notary_office: string;
            /**
             * Has Clear Title
             * @default true
             */
            has_clear_title: boolean;
            /**
             * Is Registered
             * @default true
             */
            is_registered: boolean;
            /**
             * Has Pending Lawsuits
             * @default false
             */
            has_pending_lawsuits: boolean;
            /**
             * Has Liens
             * @default false
             */
            has_liens: boolean;
            /**
             * Has Usufruct
             * @default false
             */
            has_usufruct: boolean;
            /**
             * Is In App
             * @default false
             */
            is_in_app: boolean;
            /**
             * Is In Apa
             * @default false
             */
            is_in_apa: boolean;
            /**
             * Is In Reserve
             * @default false
             */
            is_in_reserve: boolean;
            /**
             * Has Contamination
             * @default false
             */
            has_contamination: boolean;
            /**
             * Requires Environmental Study
             * @default false
             */
            requires_environmental_study: boolean;
            /** Has Environmental License */
            has_environmental_license?: boolean | null;
            /**
             * Complies With Zoning
             * @default true
             */
            complies_with_zoning: boolean;
            /**
             * Complies With Master Plan
             * @default true
             */
            complies_with_master_plan: boolean;
            /**
             * Has Building Restrictions
             * @default false
             */
            has_building_restrictions: boolean;
            /**
             * Has Heritage Protection
             * @default false
             */
            has_heritage_protection: boolean;
            /**
             * Requires Eia Rima
             * @default false
             */
            requires_eia_rima: boolean;
            /**
             * Has Iptu Debt
             * @default false
             */
            has_iptu_debt: boolean;
            /**
             * Has Itr Debt
             * @default false
             */
            has_itr_debt: boolean;
            /**
             * Has Tax Liens
             * @default false
             */
            has_tax_liens: boolean;
            /**
             * Tax Debt Amount
             * @default 0
             */
            tax_debt_amount: number;
            /**
             * Pending Lawsuits Count
             * @default 0
             */
            pending_lawsuits_count: number;
            /**
             * Has Adverse Possession Claims
             * @default false
             */
            has_adverse_possession_claims: boolean;
            /**
             * Has Expropriation Risk
             * @default false
             */
            has_expropriation_risk: boolean;
            /**
             * Has Neighborhood Disputes
             * @default false
             */
            has_neighborhood_disputes: boolean;
            /**
             * Has Updated Registration
             * @default true
             */
            has_updated_registration: boolean;
            /**
             * Has Topographic Survey
             * @default false
             */
            has_topographic_survey: boolean;
            /**
             * Has Georeferencing
             * @default false
             */
            has_georeferencing: boolean;
        };
        /**
         * P6Request
         * @description P6 Analysis Request.
         */
        P6Request: {
            /** Municipality */
            municipality: string;
            /**
             * Influence Area Population
             * @default 50000
             */
            influence_area_population: number;
            /**
             * Average Household Income
             * @default 5000
             */
            average_household_income: number;
            /**
             * Target Segment
             * @default MEDIO
             */
            target_segment: string;
            /**
             * Unit Price Min
             * @default 150000
             */
            unit_price_min: number;
            /**
             * Unit Price Max
             * @default 250000
             */
            unit_price_max: number;
            /**
             * Unit Type
             * @default LOTE
             */
            unit_type: string;
        };
        /**
         * P7Request
         * @description P7 Analysis Request.
         */
        P7Request: {
            /** Municipality */
            municipality: string;
            /**
             * Influence Area Km
             * @default 5
             */
            influence_area_km: number;
            /**
             * Competitors
             * @default []
             */
            competitors: components["schemas"]["CompetitorInput"][];
            /** Market Average Price Sqm */
            market_average_price_sqm?: number | null;
        };
        /**
         * P8Request
         * @description P8 Analysis Request.
         */
        P8Request: {
            /** Municipality */
            municipality: string;
            /**
             * Project Units
             * @default 30
             */
            project_units: number;
            /**
             * Project Price Avg
             * @default 180000
             */
            project_price_avg: number;
            /**
             * Qualified Demand
             * @default 200
             */
            qualified_demand: number;
            /**
             * Active Inventory
             * @default 50
             */
            active_inventory: number;
            /**
             * Market Vso Monthly
             * @default 0.08
             */
            market_vso_monthly: number;
        };
        /**
         * P9Request
         * @description P9 Analysis Request.
         */
        P9Request: {
            /** Municipality */
            municipality: string;
            /**
             * Qualified Demand
             * @default 200
             */
            qualified_demand: number;
            /**
             * Active Inventory
             * @default 50
             */
            active_inventory: number;
            /**
             * Competitors Count
             * @default 3
             */
            competitors_count: number;
            /**
             * Projected Absorption Months
             * @default 24
             */
            projected_absorption_months: number;
            /**
             * Project Units
             * @default 30
             */
            project_units: number;
            /**
             * Project Price Sqm
             * @default 300
             */
            project_price_sqm: number;
            /**
             * Market Price Sqm
             * @default 280
             */
            market_price_sqm: number;
        };
        /**
         * ProductType
         * @enum {string}
         */
        ProductType: "LOTEAMENTO_ABERTO" | "CONDOMINIO_FECHADO" | "VERTICAL_RESIDENCIAL" | "VERTICAL_COMERCIAL" | "MISTO";
        /** ProjectTIV */
        ProjectTIV: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Municipality
             * @description City of the project
             * @default Belo Horizonte
             */
            municipality: string;
            /**
             * @default {
             *       "certification": "NONE",
             *       "green_premium": 0,
             *       "brown_discount": 0
             *     }
             */
            esg: components["schemas"]["ESGAttributes"];
            real_options?: components["schemas"]["RealOptionsInput"] | null;
            p1?: components["schemas"]["P1GarimpoOutput"] | null;
            /**
             * Is Mixed Use
             * @default false
             */
            is_mixed_use: boolean;
            /**
             * Separate Access Cores
             * @default true
             */
            separate_access_cores: boolean;
            /**
             * Fire Load Category
             * @default Residencial
             */
            fire_load_category: string;
            /**
             * Efficiency
             * @description Project efficiency (Sellable / Total Area)
             * @default 0.85
             */
            efficiency: number;
            p4?: components["schemas"]["P4VocationOutput"] | null;
            p10?: components["schemas"]["P10FinancialOutput-Input"] | null;
            financial_input?: components["schemas"]["P10FinancialInput"] | null;
        };
        /** RealOptionsInput */
        RealOptionsInput: {
            /** Land Value Current */
            land_value_current: number;
            /** Development Cost Forcing */
            development_cost_forcing: number;
            /** Time To Permit Years */
            time_to_permit_years: number;
            /**
             * Volatility
             * @default 0.2
             */
            volatility: number;
            /**
             * Risk Free Rate
             * @default 0.11
             */
            risk_free_rate: number;
        };
        /** SimulationResponse */
        SimulationResponse: {
            /** Simulation Id */
            simulation_id: string;
            status: components["schemas"]["SimulationStatus"];
            result?: components["schemas"]["P10FinancialOutput-Output"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * SimulationStatus
         * @enum {string}
         */
        SimulationStatus: "PENDING" | "PROCESSING" | "COMPLETED" | "FAILED";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WizardSessionCreate
         * @description Create a new wizard session.
         */
        WizardSessionCreate: {
            /** Project Name */
            project_name: string;
            /** Municipality */
            municipality: string;
        };
        /**
         * WizardStepSave
         * @description Save step data to session.
         */
        WizardStepSave: {
            /** Session Id */
            session_id: string;
            /** Step */
            step: string;
            /** Data */
            data: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_opportunity_p1_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["P1GarimpoInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["P1GarimpoOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_thesis_analyze_thesis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_p2_economic_wizard_p2_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["P2Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_p4_vocation_wizard_p4_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["P4Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_p5_legal_wizard_p5_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["P5Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_p6_demand_wizard_p6_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["P6Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_p7_supply_wizard_p7_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["P7Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_p8_absorption_wizard_p8_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["P8Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_p9_validation_wizard_p9_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["P9Request"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_wizard_session_wizard_session_create_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WizardSessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_wizard_step_wizard_session_save_step_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WizardStepSave"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wizard_session_wizard_session__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_wizard_session_wizard_session__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_wizard_sessions_wizard_sessions_get: {
        parameters: {
            query?: {
                status?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_wizard_session_wizard_session__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_cache_metrics_metrics_cache_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_simulations_simulations_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recent_simulations_simulations_recent_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulation_simulation__simulation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                simulation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_simulation_status_simulation__simulation_id__stream_get: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: never;
            path: {
                simulation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calculate_quick_calculate_quick_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectTIV"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_info_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
